# This is a basic workflow to help you get started with Actions

name: CI-Stage

# Controls when the action will run.
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_Stage_CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: /.
        dst_path: /content/
        dst_owner: aspose
        dst_repo_name: aspose-repository-hugo
        dst_branch: stage
        src_branch: stage

    - name: Check out other private repo
      uses: actions/checkout@v3
      with:
        repository: Aspose/aspose-repository-hugo
        path: aspose-repository-hugo
        token: ${{ secrets.REPO_TOKEN }}
        ref: stage
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

   # Step 3 - Sets up the latest version of Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
       hugo-version: 'latest'

# Also specifies the theme we want to use
    - name: Build
      run: |
       cd /home/runner/work/aspose-repository/aspose-repository/aspose-repository-hugo
       hugo --config="config-stage.toml" -b "https://repository-stage.aspose.com/" --cleanDestinationDir --minify

    - name: Deploy total to S3
      run: |
       cd /home/runner/work/aspose-repository/aspose-repository/aspose-repository-hugo
       hugo deploy --config "./config-stage.toml"  --target "Home" --maxDeletes=-1 --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
