# This is a basic workflow to help you get started with Actions

name: CopyChangesToMainRepo

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the stage branch
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_Copycat:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.REPO_TOKEN }}
        src_path: /.
        dst_path: /content/
        dst_owner: aspose
        dst_repo_name: aspose-repository-hugo
        dst_branch: stage
        src_branch: stage
